// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import IPRNG = require('nnet/math/IPRNG');
export import NativeRandomGenerator = require('nnet/math/NativeRandomGenerator');
export import Random = require('nnet/math/Random');
export import asUnsigned = require('nnet/math/asUnsigned');
export import clamp = require('nnet/math/clamp');
export import distance = require('nnet/math/distance');
export import matchSign = require('nnet/math/matchSign');
export import mean = require('nnet/math/mean');
export import sign = require('nnet/math/sign');
export import toDegrees = require('nnet/math/toDegrees');
export import toRadians = require('nnet/math/toRadians');
export import wrapAngleDegrees = require('nnet/math/wrapAngleDegrees');
export import wrapAngleRadians = require('nnet/math/wrapAngleRadians');
