// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED
// see: "generate-module-roots-ts" task in gulpfile.js

export import IJsonSerializable = require('nnet/util/serialization/json/IJsonSerializable');
export import JsonParser = require('nnet/util/serialization/json/JsonParser');
