// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import getSize = require('./window/getSize');
export import jump = require('./window/jump');
export import origin = require('./window/origin');
export import parseQueryString = require('./window/parseQueryString');
export import replaceQueryString = require('./window/replaceQueryString');
