// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import clone = require('./object/clone');
export import extendPrototype = require('./object/extendPrototype');
export import forEach = require('./object/forEach');
export import join = require('./object/join');
export import keys = require('./object/keys');
export import map = require('./object/map');
