// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import camelCase = require('./stringutil/camelCase');
export import charTimes = require('./stringutil/charTimes');
export import contains = require('./stringutil/contains');
export import escapeHTML = require('./stringutil/escapeHTML');
export import escapeRegExp = require('./stringutil/escapeRegExp');
export import hyphenate = require('./stringutil/hyphenate');
export import stripTags = require('./stringutil/stripTags');
export import trim = require('./stringutil/trim');
export import trimChars = require('./stringutil/trimChars');
export import unescapeHTML = require('./stringutil/unescapeHTML');
