// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import IPRNG = require('./math/IPRNG');
export import NativeRandomGenerator = require('./math/NativeRandomGenerator');
export import Random = require('./math/Random');
export import asUnsigned = require('./math/asUnsigned');
export import clamp = require('./math/clamp');
export import distance = require('./math/distance');
export import matchSign = require('./math/matchSign');
export import mean = require('./math/mean');
export import sign = require('./math/sign');
export import toDegrees = require('./math/toDegrees');
export import toRadians = require('./math/toRadians');
export import wrapAngleDegrees = require('./math/wrapAngleDegrees');
export import wrapAngleRadians = require('./math/wrapAngleRadians');
