// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import flatten = require('nnet/util/array/flatten');
export import last = require('nnet/util/array/last');
export import makeRange = require('nnet/util/array/makeRange');
export import map = require('nnet/util/array/map');
export import shuffle = require('nnet/util/array/shuffle');
export import toArray = require('nnet/util/array/toArray');
