// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import first = require('./array/first');
export import flatten = require('./array/flatten');
export import isArrayLike = require('./array/isArrayLike');
export import last = require('./array/last');
export import makeRange = require('./array/makeRange');
export import map = require('./array/map');
export import shuffle = require('./array/shuffle');
export import toArray = require('./array/toArray');