// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import contains = require('./string/contains');
export import escapeHTML = require('./string/escapeHTML');
export import escapeRegExp = require('./string/escapeRegExp');
export import stripTags = require('./string/stripTags');
export import trim = require('./string/trim');
export import unescapeHTML = require('./string/unescapeHTML');
