// Copyright Malachi Griffie <malachi@nexussays.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.


// THIS FILE IS AUTOMATICALLY GENERATED

export import contains = require('nnet/util/string/contains');
export import escapeHTML = require('nnet/util/string/escapeHTML');
export import escapeRegExp = require('nnet/util/string/escapeRegExp');
export import stripTags = require('nnet/util/string/stripTags');
export import trim = require('nnet/util/string/trim');
export import unescapeHTML = require('nnet/util/string/unescapeHTML');
